# Generated by Django 4.2.1 on 2023-05-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subsystem", "0003_remove_actuator_unique_name_remove_actuator_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="actuator", name="subsystem",),
        migrations.RemoveField(model_name="sensor", name="subsystem",),
    ]
